### ISSUE TITLE
Execution duration based tests may fail even when the tested code is correct

### ISSUE THREAD

**Issue by andruekonst** [NTAILab/bosk#43]
Tests based on execution duration may fail occasionally.

Let's consider two procedures (functions): `A` and `B`; and the case when the duration of A is less than duration of B: `d(A) < d(B)`.
We cannot measure the duration `d(A)` and `d(B)` in the identical conditions, because the environment is not static (OS, other processes, etc.). In the real life we only measure duration `d(A) + eps_A` and `d(B) + eps_B`, where `eps_*` are random, so if we compare the measurements `d(A) + eps_A < d(B) + eps_B`, and the tested assumption is correct (`d(A) < d(B)` i.e. `d(B) = d(A) + p`, where `p > 0`) the test would fail if `eps_A >= p + eps_B`.

Therefore the following code is not correct:
https://github.com/NTAILab/bosk/blob/2cb191afda133c5a67c05e095759d9d8d2e90154/tests/comparison/comparison_test.py#L255

**Comment by Stasychbr** [comment]
I totally agree that for the general task of performance measurements we should operate with some sort of statistics (mean values of times or more robust median), but for this particular test the conditions (i.e. the pipelines) were selected in such way that if the optimization is proceeded correctly, the assertion must be satisfied. For example, I've just run the test, and for my system `optim_time` is 0.25 s. and `unoptim_time` is 0.56 s. (the difference is more than twice!). I assume that the `Optimization was useless` assertion description is misleading, but the purpose of the test is to check whether the optimization mechamism works at all.

I prepare future pull request for the `comparison` subpackage, so I can handle this trouble myself. According to the above, there are several options I can offer:
1. Remove this assertion (but in this way I hardly understand how to easily perform the check of the optimization mechanism)
2. Replace the assertion description with the conscious one
3. Replace the system-wide timer with the one that counts the cpu-time to avoid some things that you described
4. Make experiment with several iterations and then count the mean time (but in this case this simple unit test will take much time)

What should I do?

**Comment by andruekonst** [comment]
First of all, I've opened this issue because the test failed on my laptop, so the bug is real and difference between these durations can have order of random measurements error.
From the other side, as you mentioned, this order is too large to be able to repeat test multiple times (even taking into account that it can be parallelized), and the test can't be considered as a classical (deterministic) unit test.

I think that the solution is to:

1. Replace time with some abstract metric of computational cost (e.g. in this case number of blocks to execute), if it is possible and easy to do;
2. Otherwise to replace total execution time with ticks count (prefer single-threaded blocks in a pipeline), if it is possible and easy to do;
3. Otherwise to remove this assertion, because when a test fail with a message like "_Test can fail_" it is hard to handle results.

**Comment by Stasychbr** [comment]
Fixed this issue in the commit https://github.com/NTAILab/bosk/commit/ade53599dc11705c5bb01b96461469f58f05de01
